name       : python-confuse
version    : 2.0.0
release    : 8
source     :
    - https://pypi.io/packages/source/c/confuse/confuse-2.0.0.tar.gz : acc57c45ec2a9850a90fe7c29812bbdd8405e48a49c1a22899df915d0aca941f
homepage   : https://github.com/beetbox/confuse
license    : MIT
component  : programming.python
summary    : Painless YAML config files for Python
description: |
    Confuse is a configuration library for Python that uses YAML. It takes care of defaults, overrides, type checking, command-line integration, human-readable errors, and standard OS-specific locations.
builddeps  :
    - python-build
    - python-flit-core
    - python-installer
    - python-pytest
    - pyyaml
rundeps    :
    - pyyaml
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
