name       : python-confuse
version    : 1.4.0
release    : 4
source     :
    - https://pypi.io/packages/source/c/confuse/confuse-1.4.0.tar.gz : 92fc0451c6e2c2732ac363d0f59d7ea608abddbed062dda8e98e9a8c986ce464
license    : MIT
component  : programming.python
summary    : Confuse is a configuration library for Python that uses YAML. It takes care of defaults, overrides, type checking, command-line integration, human-readable errors, and standard OS-specific
    locations.
description: |
    Confuse is a configuration library for Python that uses YAML. It takes care of defaults, overrides, type checking, command-line integration, human-readable errors, and standard OS-specific locations.
builddeps  :
    - pyyaml
rundeps    :
    - pyyaml
build      : |
    %python3_setup
install    : |
    %python3_install
