name       : python-confuse
version    : 1.6.0
release    : 5
source     :
    - https://pypi.io/packages/source/c/confuse/confuse-1.6.0.tar.gz : d60104c0b2a708041ac27487fa6ee69bd37d910549659c7ba92f52cbe2ced4dc
license    : MIT
component  : programming.python
summary    : Confuse is a configuration library for Python that uses YAML. It takes care of defaults, overrides, type checking, command-line integration, human-readable errors, and standard OS-specific
    locations.
description: |
    Confuse is a configuration library for Python that uses YAML. It takes care of defaults, overrides, type checking, command-line integration, human-readable errors, and standard OS-specific locations.
builddeps  :
    - python-pytest
    - pyyaml
rundeps    :
    - pyyaml
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
