name       : python-confuse
version    : 1.0.0
release    : 1
source     :
    - https://github.com/beetbox/confuse/archive/v1.0.0.tar.gz : a86b0a7d1948654504017c35d493aaef3aa6fd47fdf2bdc989e742b6ee9b9e0b
license    : MIT
component  : programming.python
summary    : Confuse is a configuration library for Python that uses YAML. It takes care of defaults, overrides, type checking, command-line integration, human-readable errors, and standard OS-specific locations.
description: |
    Confuse is a configuration library for Python that uses YAML. It takes care of defaults, overrides, type checking, command-line integration, human-readable errors, and standard OS-specific locations.
builddeps  :
    - pyyaml
rundeps    :
    - pyyaml
build      : |
    %python3_setup
install    : |
    %python3_install
